before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - windows
      - linux
      - darwin
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -s -w -X main.commit={{.ShortCommit}}
      - -s -w -X main.Date={{.CommitDate}}

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage: https://smartpcr.io/imagebuilder
    description: >-
      Build golden images for hybrid-compute environments
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/nfpm/copyright
        file_info:
          mode: 0644

sboms:
  - artifacts: archive

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: imagebuilder
    homepage: https://smartpcr.io
    tap:
      owner: smartpcr-io
      name: homebrew-imagebuilder

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'